### ISSUE TITLE
Crash when start 

### ISSUE THREAD

**Issue by chanshunli** [ml-explore/mlx-swift-examples#101]
my project code : https://github.com/chanshunli/autogui_llm (follow https://github.com/ml-explore/mlx-swift-examples/tree/main/Applications/LLMEval).
I can't import LLM, I can only import MLXLLM, but it gives an error:

![image](https://github.com/user-attachments/assets/34004379-1693-4bf8-b173-7fdb0adf2242)

**Comment by chanshunli** [comment]
When I run real iphone 12, it's will crash , get this erro:

<img width="1052" alt="Screenshot 2024-08-10 at 17 15 53" src="https://github.com/user-attachments/assets/b3298c4c-a940-4b7b-8a0b-684ced6d3e98">

**Comment by chanshunli** [comment]
I run `ModelConfiguration.phi4bit` is success, but use other apps like 'local chat' , it's can run gemma2b. why?

**Comment by davidkoski** [comment]
The first issue is about running on the simulator -- it isn't supported because it doesn't emulate enough of the GPU:

- https://swiftpackageindex.com/ml-explore/mlx-swift/main/documentation/mlx/running-on-ios#Developing-for-iOS

**Comment by davidkoski** [comment]
As to the second, it is all about memory -- these models are large and take a significant amount of memory and the error you see indicates you exceeded what iOS is letting you use.  

I have a iPhone 12 Pro Max and it can run these models, but if you have just a iPhone 12 it may have less memory.

One other thing to check is this entitlement (from [here](https://swiftpackageindex.com/ml-explore/mlx-swift/main/documentation/mlx/running-on-ios)):

> Finally, if the device your code runs on has more RAM than the jetsam limit would normally allow, you can use the [Increased Memory Limit](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_kernel_increased-memory-limit) entitlement.

If all of that is in place but the larger model doesn't work, then your device just doesn't have enough RAM to evaluate it.

**Comment by chanshunli** [comment]
Thanks @davidkoski 🌹
