### ISSUE TITLE
MLX/Transforms+Eval.swift:166: Fatal error: Unable to extract MLXArray from idle

### ISSUE THREAD

**Issue by aPaleBlueDot** [ml-explore/mlx-swift-examples#102]
I can't figure what I'm doing wrong to get this error. It occurs with both downloaded and locally saved models. Tried these 3 `ModelConfiguration` s: 
```
gemma2bQuantized
mistral7B4bit
phi3_4bit
```

**Comment by davidkoski** [comment]
The error comes from here:

```swift
private func collect(_ item: Any, into arrays: inout [MLXArray]) {
...
    default:
        fatalError("Unable to extract MLXArray from \(item)")
```

This is complaining about a value passed in to `eval()` or `asyncEval()`.  Based on the `idle` I suspect it is probably this:

```swift
    enum LoadState {
        case idle
        case loaded(ModelContainer)
    }
```

but how that gets passed in ..., that is a bit of a mystery.  I suggest putting a breakpoint on that line (MLX/Transforms+Eval.swift:166) and looking at what calls it.

**Comment by aPaleBlueDot** [comment]
Indeed, somehow the model is probably not getting loaded. It's very likely that my Xcode config is incorrect, as it's untouched example code that gives this error. Putting a breakpoint now.

**Comment by davidkoski** [comment]
You may be missing entitlements for network access (to download the weights)

**Comment by aPaleBlueDot** [comment]
It downloads the model directory from HF before this error. I later switched to using a local folder, though nothing changed. Also noticed another warning prior to this one: BOOL _NSPersistentUIDeleteItemAtFileURL(NSURL *const __strong) Failed to stat item: file:///Users/hg/Library/Containers/mlx.LoRATrainingExample.GH/Data/Library/Saved%20Application%20State/mlx.LoRATrainingExample.GH.savedState/restorecount.plist

**Comment by aPaleBlueDot** [comment]
Attaching the screenshot of the call stack right before this exception is thrown. 
![Screenshot 2024-08-10 at 18 31 48](https://github.com/user-attachments/assets/fa5eda0d-80b7-460f-9c93-95ddf489d13f)
![Screenshot 2024-08-10 at 18 31 41](https://github.com/user-attachments/assets/514654e2-cd7f-41fb-942b-5d61ea4a8440)
![Screenshot 2024-08-10 at 18 31 35](https://github.com/user-attachments/assets/464745cd-bbd4-400b-901a-dd9b35dd73e7)
![Screenshot 2024-08-10 at 18 31 25](https://github.com/user-attachments/assets/16679588-f114-493e-9661-65f846edd856)
![Screenshot 2024-08-10 at 18 31 12](https://github.com/user-attachments/assets/7e60e756-456b-4a60-b13e-d63a3c5eaad9)
![Screenshot 2024-08-10 at 18 31 02](https://github.com/user-attachments/assets/f962336c-3f28-4d6e-bb18-ad0734e62149)

**Comment by davidkoski** [comment]
Ah, I see.  Delete this line in `LoRAEvaluator.loadModel()`:

```swift
            eval(model)
```

I will prepare a PR for that, but in the meantime that should improve things -- we don't need that line.

**Comment by davidkoski** [comment]
Thank you for reporting this and helping to find the cause!

**Comment by aPaleBlueDot** [comment]
Thank *you* for your spotting it in the blink of an eye. This team rocks!
