### ISSUE TITLE
Gigabyte top ai  utility

### ISSUE THREAD

**Issue by Isaina** [ml-explore/mlx-swift-examples#105]
Hi, can you also write as example tool for fine tunings llm like gigabyte ai to utility 

https://www.gigabyte.com/Press/News/2201

**Comment by davidkoski** [comment]
I don't know what kind of fine tuning they do, but check out:

- https://github.com/ml-explore/mlx-swift-examples/blob/main/Tools/llm-tool/README.md#lora

That is fine tuning using LoRA (https://arxiv.org/abs/2106.09685)

**Comment by davidkoski** [comment]
Closing issue, but if you have more information please reopen or file a new issue!
