### ISSUE TITLE
What's the right way to include a model's directory in an app?

### ISSUE THREAD

**Issue by aPaleBlueDot** [ml-explore/mlx-swift-examples#112]
For development purposes, I'd like to simply include an MLX converted model folder in the app.  I'm a rookie in all things iOS/Xcode, so I've tried 4 things, with no luck:

`directory:  Bundle.main.url(forResource:"Data/model_folder", withExtension: nil)!,`
as well as 
`directory:  Bundle.main.url(forResource:"model_folder", withExtension: nil)!,`
applying 
"Convert to Group" and "Convert to Folder" on the  `model_folder` . 

Any help would be greatly appreciated.

**Comment by aPaleBlueDot** [comment]
Resolved.

**Comment by zach-withcoherence** [comment]
@aPaleBlueDot what did you do to solve this? thanks!

**Comment by aPaleBlueDot** [comment]
> @aPaleBlueDot what did you do to solve this? thanks!

Hey @zach-withcoherence, here's what worked, if I remember correctly:
1) Click on the root of your project on the left hand side navigation. 
2) Under the TARGETS column select LLMEval 
3) Click on the Build Phases tab 
4) Go to the Copy Bundle Resources section 
5) Click the + sign to add your model folder
