### ISSUE TITLE
LLMEval doesn’t work offline

### ISSUE THREAD

**Issue by 3Samourai** [ml-explore/mlx-swift-examples#113]
After the first start, it would be logical for the app not to make new requests, since all data has been downloaded. However, if you try to run the models on a device that is not connected to internet, you get an error.

**Comment by davidkoski** [comment]
It is probably checking for updates of the model files -- I will track it down, I agree it should be happy to run.

**Comment by mobile-appz** [comment]
> It is probably checking for updates of the model files -- I will track it down, I agree it should be happy to run.

Was there any progress with this please? I don't know how to fix it but looks like there should be a fall back option if the model already exists on the device but there is no connectivity when it looks for filenames in the getFilenames() method.

**Comment by davidkoski** [comment]
No, I haven't had a chance to look at it yet.

**Comment by davidkoski** [comment]
But thanks for the reminder! -- check out #133

**Comment by mobile-appz** [comment]
> But thanks for the reminder! -- check out #133

Thanks, great work
