### ISSUE TITLE
Update to swift-transformers

### ISSUE THREAD

**Issue by maiqingqiang** [ml-explore/mlx-swift-examples#117]
Hi @davidkoski @awni !
Is it possible to upgrade the dependencies? 

The latest version of [swift-transformers](https://github.com/huggingface/swift-transformers) supports chat-template. https://github.com/huggingface/swift-transformers/pull/104

[ChatMLX](https://github.com/maiqingqiang/ChatMLX) depends on mlx-libraries and the latest version of [swift-transformers](https://github.com/huggingface/swift-transformers), but mlx-libraries uses an older swift-transformers version. Looking forward to an upgrade.
https://github.com/ml-explore/mlx-swift-examples/blob/9266a6282fc56e1be03292cde6e665b765fb977b/Package.swift#L19

After upgrading, you can also modify Libraries/LLM/Models.swift. https://github.com/ml-explore/mlx-swift-examples/blob/9266a6282fc56e1be03292cde6e665b765fb977b/Libraries/LLM/Models.swift#L115-L237

**Comment by davidkoski** [comment]
Yes of course!  If you want to submit a PR that is the fastest way, otherwise I will try to get to this in the coming week.

**Comment by maiqingqiang** [comment]
Okay, thank you very much @davidkoski! 
I can only modify [mlx-swift-examples/Package.swift](https://github.com/ml-explore/mlx-swift-examples/blob/9266a6282fc56e1be03292cde6e665b765fb977b/Package.swift#L19) on my end. 

As for modifying [mlx-swift-examples/Libraries/LLM/Models.swift](https://github.com/ml-explore/mlx-swift-examples/blob/9266a6282fc56e1be03292cde6e665b765fb977b/Libraries/LLM/Models.swift#L115-L237), I might not have time for that at the moment.

Hi @pcuenca, could you please tag a new release for https://github.com/huggingface/swift-transformers?

**Comment by davidkoski** [comment]
I think we are all set here
