### ISSUE TITLE
Phi-3.5-mini-instruct complains about "rope_scaling"

### ISSUE THREAD

**Issue by aPaleBlueDot** [ml-explore/mlx-swift-examples#127]
Same root cause as that of [issue #92](https://github.com/ml-explore/mlx-swift-examples/issues/92) 

typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "rope_scaling", intValue: nil), _CodingKey(stringValue: "long_factor", intValue: nil)]

It's a pity, as phi-3.5 comes with a lot of goodies.

**Comment by DePasqualeOrg** [comment]
I never had this issue with Phi-3.5 mini, but you can check if https://github.com/ml-explore/mlx-swift-examples/pull/155 fixes this for you.

**Comment by davidkoski** [comment]
StringOrNumber has been enhanced: 

- https://github.com/ml-explore/mlx-swift-examples/blob/main/Libraries/MLXLMCommon/StringOrNumber.swift

let me see if this is still a problem

**Comment by davidkoski** [comment]
Looks good!

```
./mlx-run llm-tool --model mlx-community/Phi-3.5-mini-instruct-8bit --prompt "Why is the sky blue?"
```

```
Why is the sky blue? The sky appears blue to the human eye due to a phenomenon called Rayleigh scattering. This occurs when sunlight enters Earth's atmosphere and interacts with the gases and particles in it. Sunlight is made up of a spectrum of colors, and when it reaches the atmosphere, it is scattered in all directions by the gases and particles. Blue light is scattered more than other colors because it travels as shorter, smaller waves. This scattering process causes the blue light to```

**Comment by davidkoski** [comment]
oh and it looks like we already had a preset for it:

```swift
    static public let phi3_5_4bit = ModelConfiguration(
        id: "mlx-community/Phi-3.5-mini-instruct-4bit",
        defaultPrompt: "What is the gravity on Mars and the moon?",
        extraEOSTokens: ["<|end|>"]
    )
```
