### ISSUE TITLE
Crash on launch of the application

### ISSUE THREAD

**Issue by venkadesh-p** [ml-explore/mlx-swift-examples#139]
Hello, I am trying to run the LLMEval into iPhone 16 Pro simulator and the Xcode version is 16.0. But I am getting crash at the launch of the application. I have attached the crash screenshot here. Can anyone please help me to resolve this issue?
I am running it on Macbook Air M2 8GB RAM and macOS Sequoia 15.1 Beta

<img width="1461" alt="Screenshot 2024-10-04 at 2 01 36 PM" src="https://github.com/user-attachments/assets/a64a43f0-f69c-46f5-ac13-c9c16817e204">

**Comment by davidkoski** [comment]
The iOS simulator isn't supported as it doesn't emulate the right level of GPU, but see some tips here:

- https://swiftpackageindex.com/ml-explore/mlx-swift/main/documentation/mlx/running-on-ios#Developing-for-iOS
