### ISSUE TITLE
Xcode refuses to build or do anything after adding https://github.com/ml-explore/mlx-swift-examples/ as dependency

### ISSUE THREAD

**Issue by coratype** [ml-explore/mlx-swift-examples#145]
created a new project in Xcode, completely blank slate, added the

https://github.com/ml-explore/mlx-swift-examples/

dependency as the readme says, and the build just refuses to build. no error or anything, just doesnt do anything?

edit: randomly decides to build, but when i try to "import LLM" it says no such module LLM

**Comment by davidkoski** [comment]
You will need to set up targets in your project and set dependencies on the libraries provided by mlx-swift-examples. S something like this:

<img width="798" alt="image" src="https://github.com/user-attachments/assets/d42fbe34-3296-47b9-8219-f4ceb526b3f2">

**Comment by davedelong** [comment]
I'm also hitting the "no such module 'LLM'" error and am quite baffled as to why.

**Comment by davidkoski** [comment]
If you are getting it via the swiftpm file (Package.swift) then it is called `MLXLLM` (to better match the mlx-swift libraries):

```
        .library(
            name: "LLM",
            targets: ["MLXLLM"]),
```

I am working on VLM support in #151 and part of that will make this much more consistent.

**Comment by davedelong** [comment]
I've added it as a package dependency in Xcode 15.4. Xcode recognizes the LLM product and can add it as a dependency to my other targets, but when I compile it has the missing module error. I _think_ this might be flaw in the Xcode build system related to the mismatch between the library name ("LLM") and the target name ("MLXLLM"). I'm continuing to investigate.

**Comment by davidkoski** [comment]
OK, let me know what you find out -- I think we should probably make the directory/target/library/module all match.  The mismatch was from the Project.swift but I think whoever set that up had the better idea.

**Comment by davedelong** [comment]
ok, so I just tried a private fork of `mlx-swift-examples` that only changed [the library name](https://github.com/ml-explore/mlx-swift-examples/blob/main/Package.swift#L11) from `LLM` to `MLXLLM` and Xcode 15.4 had no problems.

**Comment by rudrankriyam** [comment]
Follow up on this: I tried in an existing/new project and if I use `import MLXLLM` instead of `import LLM` and use `MLXLLM.generate` etc, it works fine. Even in a Swift package.

**Comment by davidkoski** [comment]
The naming differences have been corrected -- it is `import MLXLLM` everywhere now.  Hopefully that clears up a lot of confusion (that was not at all obvious!)
