### ISSUE TITLE
Has anyone successfully run Whisper in Swift?

### ISSUE THREAD

**Issue by AmanKishore** [ml-explore/mlx-swift-examples#146]
Looking to see if anyone has an example on how to run whisper with swift!

**Comment by davidkoski** [comment]
Check out https://github.com/argmaxinc/WhisperKit -- that is in swift and they have a branch & PR for using MLX

**Comment by zshannon** [comment]
Can this get re-opened? WhisperKit does a lot more stuff vs the mlx-example implementation of Whisper in Python. It's not staying up to date on dependencies, and their stated business goals aren't aligned with eg having a solid reference implementation of whisper using MLX in swift

**Comment by hongbo-miao** [comment]
https://github.com/Blaizzy/mlx-audio seems based on MLX framework.

**Comment by DePasqualeOrg** [comment]
I have an implementation of Whisper in Swift here, which is already working pretty well and will continue to improve: https://github.com/DePasqualeOrg/mlx-swift-audio
