### ISSUE TITLE
[Bug] Llama 3 DynamicNTK RoPE is incorrect

### ISSUE THREAD

**Issue by awni** [ml-explore/mlx-swift-examples#152]
It's basically just wrong.. but works well enough for short sequences that it's not noticeable. We should follow the [Python implementation](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/models/llama.py#L51-L117).

**Comment by DePasqualeOrg** [comment]
Sorry about that. I think that was my mistake. I've fixed this in https://github.com/ml-explore/mlx-swift-examples/pull/154.

**Comment by davidkoski** [comment]
This is merged
