### ISSUE TITLE
Add Example  for VLM

### ISSUE THREAD

**Issue by rudrankriyam** [ml-explore/mlx-swift-examples#164]
Hi! Thank you for adding VLM support! I [played around](https://www.rudrank.com/exploring-mlx-swift-adding-on-device-vision-models/) with adding a model to an app, and was wondering to add a `VLMEval` project!

Wanted to ask if that is something in works, otherwise I can pick it up, creating something similar to `LLMEval`!

**Comment by awni** [comment]
Yea, we'd love to have that as a PR!

**Comment by rudrankriyam** [comment]
On it!
