### ISSUE TITLE
CodeLlama crashes

### ISSUE THREAD

**Issue by krzyzanowskim** [ml-explore/mlx-swift-examples#2]
llm-tool --model mlx-community/CodeLlama-13b-Instruct-hf-4bit-MLX --prompt "Hello"

> Starting generation ...
> hellolibc++abi: terminating due to uncaught exception of type std::invalid_argument: [quantized_matmul] The weight matrix should be uint32 but receivedfloat16

llm-tool --model mlx-community/CodeLlama-13b-Instruct-hf-4bit-MLX --prompt "Hello"

> backtrace: https://gist.github.com/krzyzanowskim/8f9abc9babee9152f522a4ba039ffdd3

The Python counterpart seems to work with these models:

```
$ python -m mlx_lm.generate --model mlx-community/CodeLlama-13b-Instruct-hf-4bit-MLX --prompt "Hello"
Prompt: Hello
, I am a newbie in AngularJS. I have a simple website with a form with a text input and a button to submit the form.

\begin{code}
<form ng-submit="submitForm()">
    <input type="text" ng-model="formData.name">
    <button type="submit">Send</button>
</form>
\end{code}

I want to do the following:

1)
==========
Prompt: 0.606 tokens-per-sec
Generation: 4.664 tokens-per-sec
```

PS. to make it work at all I added `"CodeLlamaTokenizer": LlamaTokenizer.self` to the [swift-transformers knownTokenizers](https://github.com/huggingface/swift-transformers/blob/564442fba36b0b694d730a62d0593e5f54043b55/Sources/Tokenizers/Tokenizer.swift#L61)

I have no idea how to make it work myself, but maybe somebody has any pointer where to start

**Comment by davidkoski** [comment]
I can start by explaining what that means.  The configuration for that model specifies that it uses quantization:

```
    // set up the model
    if let quantization = baseConfig.quantization {
        QuantizedLinear.quantize(
            model: model, groupSize: quantization.groupSize, bits: quantization.bits)
    }
```

This replaces `Linear` with `QuantizedLinear`.  Those layers use `uint32` weights rather than some variant of `Float`.

So that means when we load the weights:

```
    let weights = try loadArrays(url: modelDirectory.appending(component: "weights.00.safetensors"))
    let parameters = ModuleParameters.unflattened(weights)
    try model.update(parameters: parameters, verify: [.all])
```

some of those parameters that should have been quantized probably were not.  We can look at all of these layers:

```
    _ = model.leafModules().flattened().map { (key, layer) in
        if layer is QuantizedLinear {
            print("\(key): \(layer.parameters().mapValues { $0.dtype })")
        }
    }
```

and see:

```
lm_head: [
  biases: float32,
  scales: float32,
  weight: float16
]
```

That is the layer that is giving us grief.

**Comment by davidkoski** [comment]
Aha, and the problem is here in `mlx-examples/llms/mlx_lm/utils.py`

```
    if quantization is not None:
        # for legacy models that don't have lm_head quant due to non-32 dims
        if "lm_head.scales" not in weights.keys():
            vocab_size = config["vocab_size"]
            extended_linear_class_predicate = (
                lambda layer: linear_class_predicate(layer)
                and layer.weight.shape[0] != vocab_size
            )
            nn.QuantizedLinear.quantize_module(
                model,
                **quantization,
                linear_class_predicate=extended_linear_class_predicate,
            )
        # for models that have lm_head quant
        else:
            nn.QuantizedLinear.quantize_module(
                model,
                **quantization,
                linear_class_predicate=linear_class_predicate,
            )
```

I ported the load code from a different version of this (`mlx-examples/llms/mistral`) and it didn't have this logic.

**Comment by davidkoski** [comment]
We need this fix in `mlx-swift` for the predicate to work: https://github.com/ml-explore/mlx-swift/pull/28

**Comment by davidkoski** [comment]
I think `BPETokenizer` is actually the universal fallback.  There are really only two tokenizers:

```
class GPT2Tokenizer    : BPETokenizer {}
class FalconTokenizer  : BPETokenizer {}
class LlamaTokenizer   : BPETokenizer {}
class CodeGenTokenizer : BPETokenizer {}
class WhisperTokenizer : BPETokenizer {}

class T5Tokenizer      : UnigramTokenizer {}
```
