### ISSUE TITLE
Error running LLMEval in iOS simulator

### ISSUE THREAD

**Issue by danveloper** [ml-explore/mlx-swift-examples#21]
I receive the following error when I try to run the `LLMEval` target on iPhone 15 Pro Max in the iOS simulator:

```
MTLValidateFeatureSupport:6508: failed assertion `Dispatch Threads with Non-Uniform Threadgroup Size is not supported on this device'
```

The steps to reproduce are pretty straightforward... I select the `LLMEval` target, click the dropdown at the top to change from "Mac" to "iPhone 15 Pro Max", click the play button. The app loads, downloads the model, then when you click generate it will crash with the above message.

Important to note that this behavior does _not_ happen when running on a real iPhone (15 Pro Max, in my case). On a real device everything works fine, so I suspect it's a problem with how the simulator's GPU device is being presented.

**Comment by davidkoski** [comment]
I can reproduce with the Phi2 model.  It happens when calling `Gather::eval_gpu()`:

```
(lldb) p grid_dims
(MTL::Size)  (width = 0, height = 2560, depth = 1)

(lldb) p group_dims
(MTL::Size)  (width = 8, height = 128, depth = 1)
```

cc @jagrit06 -- any thoughts?

**Comment by awni** [comment]
Does the validation fail just in iOS or also macOS?

**Comment by davidkoski** [comment]
> Does the validation fail just in iOS or also macOS?

Neither, this is on the simulator -- it simulates iOS but is a process on macOS.  Sort of like a VM but not quite.

**Comment by danveloper** [comment]
@davidkoski also just to clarify this is running in the release mode so it’s distinct from the other issue of development tail call problems. The output you showed I observed (like the others) when running the dev build. I don’t think I saw that with this problem, just that the MTL validator rejected the device completely. (But absolutely could be wrong.)

**Comment by davidkoski** [comment]
Agreed, not the deep stack issue -- it is rejecting the parameters when submitting this metal kernel (while on the simulator).

**Comment by awni** [comment]
I don't think this is something we can fix in MLX. We rely on ``dispatchThreads` in way too many places. I'm a bit stumped as to why it fails in the sim though.

There are some devices which do not support it but according to the feature set tables (pg 9 [here](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf)) it is supported on all modern devices. Could it be a bug in the simulator?

**Comment by davidkoski** [comment]
Ah, interesting, so I tried this:

```
            if let device = Metal.MTLCreateSystemDefaultDevice() {
                
                print(device)
                
                let levels: [MTLGPUFamily] = [
                    .common1,
                    .common2,
                    .common3,
                    .metal3,
                    .apple2,
                    .apple3,
                    .apple4,
                    .apple5,
                    .apple6,
                    .apple7,
                    .apple8,
                    .apple9,
                ]
                
                for level in levels {
                    print("\(level): \(device.supportsFamily(level))")
                }
```

It is `common1` and `apple2`, neither of which support `Non-uniform threadgroup size`.

Perhaps the way to move forward is use `.cpu` on the simulator?

**Comment by davidkoski** [comment]
Potentially even make the `.cpu` the default device on the simulator.

**Comment by ainame** [comment]
I had the same problem and confirmed the workaround would be to launch the app as "Designed for iPad" as mentioned above. It works well with my app. Thanks.

**Comment by davidkoski** [comment]
OK, I will add this recommendation to the documentation, probably here:

- https://swiftpackageindex.com/ml-explore/mlx-swift/main/documentation/mlx/running-on-ios

**Comment by davidkoski** [comment]
This was added to the documentation (link above).  OK to close?

**Comment by danveloper** [comment]
Yeah thanks for diving into it
