### ISSUE TITLE
LLMEval: Model Configuration Registry Remains Empty, Preventing Dynamic Model Selection

### ISSUE THREAD

**Issue by 1-ashraful-islam** [ml-explore/mlx-swift-examples#29]
I am currently working on implementing a model picker so selecting a new model does not require recompiling the app. I was trying to use 
https://github.com/ml-explore/mlx-swift-examples/blob/0af2efe8a04d11a7c01616e560a3bd67ac38f246/Libraries/LLM/Models.swift#L39

However, I am seeing this registry that is supposed to hold the configurations for available model always stays empty, and as such I can not use this to create a model picker. I am also noticing the bootstrap function, which is intended to populate the registry, is never called either. bootstrap function is referenced in a few places in the file.
https://github.com/ml-explore/mlx-swift-examples/blob/0af2efe8a04d11a7c01616e560a3bd67ac38f246/Libraries/LLM/Models.swift#L103-L122

I'm trying to understand the original design intention behind the `registry` and whether using it to create a dynamic model picker in `ContentView` is an appropriate use case.

As someone new to Swift development, I'm unsure if I'm missing a crucial step in the implementation or if there's an issue with how the bootstrap function is supposed to be triggered. Any guidance or insights on how to correctly implement or debug this feature would be greatly appreciated.

**Comment by davidkoski** [comment]
You aren't missing anything, the implementation falls slightly short.  Perhaps `registry` should not be public (expose via a function?) or maybe it can be done with a lazy property.

Right now the only callers get to it via `ModelConfiguration.mistral7B4bit` (which will get the property directly) or via a call to `configuration(id: ...)` which will populate the registry.  There wasn't a use case where somebody used the registry directly (but clearly that seems like a reasonable thing to do).

**Comment by davidkoski** [comment]
This has been cleaned up quite a bit.  You would access this through:

```swift
let modelConfiguration = LLMModelFactory.shared.modelRegistry.configuration(id: "...")
```

There are only two public functions:

- register additional configurations
- look up a configuration by id

The registry itself is not exposed (and no longer has a bootstrap sequence, it is initialized on creation of the registry).  If there is a need to iterate the values in the registry we can certainly return the values.

That said, I don't know that having access to all the models in the registry is a good idea: not all models take the same type f prompts, produce the same type of answers, etc.  You would probably be better off having your own list that meets the needs of your application.
