### ISSUE TITLE
Any plans to create a swift-llm package?

### ISSUE THREAD

**Issue by mzbac** [ml-explore/mlx-swift-examples#31]
Thanks for creating this amazing example repository. I was just wondering if there are any plans to create a swift-llm package similar to mlx-lm so people don't have to manually copy all the code from the LLM folder into their project. This would remove some barriers for people to try out the swift-mlx. As someone new to Swift, copying and pasting LLM code from the examples and setting it up took quite a bit of time. It would be great if we could provide a package so developers don't have to go through that process.

**Comment by awni** [comment]
> I was just wondering if there are any plans to create a swift-llm package similar to mlx-lm so people don't have to manually copy all the code from the LLM folder into their project. 

Hmm, you shouldn't need to copy and paste the example unless you are trying to get rid of the other stuff like the MNIST part. You can clone the repo and open it in xcode.

**Comment by mzbac** [comment]
@awni I was using SwiftPM to create the new project. So I had to copy all the code from `Libraries/LLM`. I was thinking if it would be possible to provide a swiftPM package so that I can add it via SwiftPM like the swift-mlx: https://github.com/ml-explore/mlx-swift?tab=readme-ov-file#swiftpm

Do you mean we should use the mlx-swift-example as a template and start the new project from it? Sorry, I am quite new to Swift and Xcode, not very sure what's the best way to create a new project with swift-mlx.

**Comment by awni** [comment]
I see.. I think @davidkoski has some ideas here as well.

But basically you have a few options:
- You can use it as a git submodule (no copying required)
- You can copy the files as you did
- You can fork and use it as a template and build on it

As for a Swift package, I'm not sure. It is a good idea in principle, but would probably require splitting the LLM stuff into a new repo (?).

**Comment by davidkoski** [comment]
Here is how you might do it with Xcode:

<img width="1201" alt="image" src="https://github.com/ml-explore/mlx-swift-examples/assets/46639364/8ad9581d-341d-4fd5-8bdf-4cb75baaed25">

Notice I have dragged `mlx-swift-examples.xcodeproj` into the list of files in the project on the left.  In my target, `MyTestApp`, I can link against `LLM.framework` which is what I think you are looking for.  It will only build the pieces related to your target.

In this case I just made a project in `/tmp` and dragged it in, but you could easily use git submodules to make something that checks it all out.

Be aware that you can only have the `mlx-swift-examples` directory open once in Xcode.  If it shows up without the disclosure indicator on the left it probably means you already have it open.  Just close both windows and reopen your app.

**Comment by davidkoski** [comment]
#39 is merged -- see if that works for you.

OK to close?

**Comment by mzbac** [comment]
Awesome! Thank you. I'm happy to close it. I am currently away from my Mac, but I will try the package once I get a chance.
