### ISSUE TITLE
llm-tool failing to compile

### ISSUE THREAD

**Issue by heckj** [ml-explore/mlx-swift-examples#5]
As of commit: 3f02fcc1 (`main` branch, current head as I'm opening the issue)

the `llm-tool` target is failing to compile:

The error: `Overriding non-open instance method outside of its defining module` inside Phi.swift, screenshot:

<img width="986" alt="Screenshot 2024-02-27 at 11 13 14 AM" src="https://github.com/ml-explore/mlx-swift-examples/assets/43388/7b8dd7d5-0344-4ff8-b0fa-38373f52b0f4">

(This is using Xcode 15.3 beta 3, opening the project via `mlx-swift-examples.xcodeproj`)

**Comment by davidkoski** [comment]
You need to be at this commit in `mlx`: https://github.com/ml-explore/mlx-swift/tree/cad668ce04f397c19ddb6a74bc7ceafff4ea0314

The dependency in `mlx-swift-examples` is to the main branch -- perhaps you need to File -> Package -> Update To Latest Package Versions

**Comment by heckj** [comment]
Got it - thanks!
