### ISSUE TITLE
OpenELM example?

### ISSUE THREAD

**Issue by MatthewWaller** [ml-explore/mlx-swift-examples#55]
Thanks for the awesome work! I would request an OpenELM example. Or if we can tweak one of the existing examples for OpenELM, that would be great. Any guidance?

**Comment by mobile-appz** [comment]
Have unsucessfully tried to run the swift LLM tool with this model: mlx-community/OpenELM-1_1B-Instruct-4bit 

It's now working in MLX core with the Python code. The output is impressive for the very small model size, meaning it should offer great utility on older iOS devices with less RAM.  However, it's not working in MLX-Swift. It has the same error as per the issue below. "Error: unhandledKeys(base: "Embedding", keys: ["biases", "scales"])". So it appears that something fundamental needs to be done to get this to work at all in iOS and Swift.  

https://github.com/ml-explore/mlx-swift-examples/issues/53#issuecomment-2072250486

**Comment by davidkoski** [comment]
https://github.com/ml-explore/mlx-swift-examples/pull/63

**Comment by MatthewWaller** [comment]
Good to close when the other PR is accepted! Would love to figure out how to get the proper instruct prompt working, but I can open a different PR for that.
