### ISSUE TITLE
Phi-3 on iOS,

### ISSUE THREAD

**Issue by fromparis** [ml-explore/mlx-swift-examples#59]
impossible to run the iOS version I get :

import MLX - No such module 'MLX'

<img width="897" alt="Screenshot 2024-04-25 at 23 07 22" src="https://github.com/ml-explore/mlx-swift-examples/assets/10722282/77028f4d-6d9c-4383-a6a0-473bc1bfa57c">

**Comment by MatthewWaller** [comment]
Maybe try reset package cache? It doesn't look like your Package Dependencies on the left are all pulled yet.

**Comment by fromparis** [comment]
Package.resolved file is corrupted or malformed; fix or delete the file to continue: unknown 'PinsStorage' version '3' at '/Users/mac/Downloads/mlx-swift-examples-main 12/mlx-swift-examples.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved'.

**Comment by davidkoski** [comment]
https://github.com/ml-explore/mlx-swift-examples/blob/main/mlx-swift-examples.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

maybe this:

```
  "version" : 3
```

**Comment by davidkoski** [comment]
@fromparis -- if you get a chance see if #60 (branch `fix-package-resolved`) fixes the problem.

**Comment by fromparis** [comment]
I think it's working,
