### ISSUE TITLE
Error when running OpenELM 1b Instruct 8-bit

### ISSUE THREAD

**Issue by DePasqualeOrg** [ml-explore/mlx-swift-examples#65]
I added a configuration option for [OpenELM 1b Instruct 8-bit](https://huggingface.co/mlx-community/OpenELM-1_1B-Instruct-8bit) like so:

```swift
  public static let openelm1bInstruct8bit = ModelConfiguration(
    id: "mlx-community/OpenELM-1_1B-Instruct-8bit"
  ) { prompt in
    "\(prompt)"
  }
```

But when I run the model, I get the following error: `Failed: unhandledKeys(base: "Embedding", keys: ["biases", "scales"])`

**Comment by davidkoski** [comment]
I think this is the same as #53 -- I am still preparing the code to load these new quantized values.

**Comment by davidkoski** [comment]
#76 should fix this
