### ISSUE TITLE
`generate` silently fails on OpenELM 3B after latest commit

### ISSUE THREAD

**Issue by DePasqualeOrg** [ml-explore/mlx-swift-examples#69]
[Original comment removed, see below]

```swift
import Foundation
import MLXLLM

extension ModelConfiguration {
  static let openelm3b = ModelConfiguration(
    id: "mlx-community/OpenELM-3B"
  ) { prompt in
    "\(prompt)"
  }
}
```

**Comment by DePasqualeOrg** [comment]
After testing it with a smaller model, it appears to work, but the larger model fails without any error. Maybe it's too large for my 16 GB of RAM, but it's not crashing the app when I try to run inference. Providing error messages in the MLXLLM library and in the demo app would help debug these issues.

```swift
import Foundation
import MLXLLM

extension ModelConfiguration {
  // This one fails silently
  static let openelm3b = ModelConfiguration(
    id: "mlx-community/OpenELM-3B"
  ) { prompt in
    "\(prompt)"
  }

  // This one works
  static let openelm450mInstruct = ModelConfiguration(
    id: "mlx-community/OpenELM-450M-Instruct"
  ) { prompt in
    "\(prompt)"
  }
}
```

**Comment by DePasqualeOrg** [comment]
The silent failing of OpenELM 3B seems to be caused by commit [https://github.com/ml-explore/mlx-swift-examples/commit/ff7610d522a57e403140e8431ebd6d032dcdb86c](https://github.com/ml-explore/mlx-swift-examples/commit/ff7610d522a57e403140e8431ebd6d032dcdb86c). It doesn't happen when checking out the commit before that.

**Comment by davidkoski** [comment]
OK, #53 should address this

**Comment by davidkoski** [comment]
#76 should fix this
