### ISSUE TITLE
Publish releases with version numbers

### ISSUE THREAD

**Issue by DePasqualeOrg** [ml-explore/mlx-swift-examples#79]
I'm using the LLM libraries from this repo in an app that will soon be available for distribution, and it would be helpful to specify release versions to determine compatibility with new models as they're released and the libraries are updated to run them. Otherwise, older versions of the app might crash or not function properly if they try to run a newer model with an older, incompatible version of the libraries.

**Comment by davidkoski** [comment]
So specifically start tagging releases of mlx-swift and mlx-swift-examples?

**Comment by DePasqualeOrg** [comment]
Yes, that would be helpful. My current workaround is to specify commit hashes for those libraries, but it would be more convenient if they followed semantic versioning conventions.

**Comment by davidkoski** [comment]
OK, added 0.12.1 (matching v0.12.1 from mlx) on mlx-swift and added a PR (#80) to adopt that.  Once that is in I can tag mlx-swift-examples.

**Comment by DePasqualeOrg** [comment]
Thanks!

**Comment by davidkoski** [comment]
https://github.com/ml-explore/mlx-swift-examples/releases/tag/0.12.1
