### ISSUE TITLE
Broken, unneeded GzipSwift is blocking consumers of mlx-libraries

### ISSUE THREAD

**Issue by DePasqualeOrg** [ml-explore/mlx-swift-examples#85]
The latest release of GzipSwift is broken due to typos in the package file (https://github.com/1024jp/GzipSwift/issues/65). This package is only consumed by the MNIST target of mlx-swift-examples. I'm using mlx-libraries from this repo in my app, and it's pulling in the broken GzipSwift, which isn't needed and is blocking me from building my app. It would be great if this dependency could be removed from mlx-libraries.

Perhaps it would be best to split mlx-libraries into a separate, minimal repo, to reduce overhead and complications for consumers of this package?

**Comment by davidkoski** [comment]
Splitting the examples repo is probably a larger task and I am not sure we want to go there yet.  For this we can at least fix it by pinning it to a good release.  We don't need the latest and greatest gzip integration.

**Comment by DePasqualeOrg** [comment]
I'm happy to take on splitting out mlx-libraries into a separate repo if you'd like. I've basically already done that in my own fork of this repo, and in the example apps it would just involve changing some references to the libraries.
