### ISSUE TITLE
Things Crash on MacOS Beta

### ISSUE THREAD

**Issue by amirsafaei** [ml-explore/mlx-swift-examples#96]
Have you tried this on Sequoia ? it was working fine for me but it crashes since I updated to Mac OS Sequoia Beta.

**Comment by awni** [comment]
Could you share what you ran that crashed?

**Comment by davidkoski** [comment]
You should update `mlx-swift` to 0.16.0 -- that has fixes for Sequoia.  We haven't updated the default version here yet.

**Comment by DePasqualeOrg** [comment]
Is there a reason the default version hasn't been updated? I've been fighting Xcode for an hour, just trying to get my app to build with the various dependencies.

**Comment by davidkoski** [comment]
You can try this branch: `concurrency-1`

- https://github.com/ml-explore/mlx-swift-examples/tree/concurrency-1

That will pull in the latest mlx-swift

**Comment by davidkoski** [comment]
That is merged -- please note that I bumped the major version number to 1 since there were some breaking API changes.

**Comment by davidkoski** [comment]
Closing, I am running everything on the beta without issues -- please file a new issue if you see other issues.  I think #108 should resolve the last issue for swift 6.
